name: Thor compatibility tests

on:
  workflow_dispatch:

jobs:
  test-solo:
    name: Test Solo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sharding: [access,finance,governance,gov_timelock,gov_utils_extensions,metatx,proxy,token_ERC20,token_ERC721,token_ERC721Enumerable,token_ERC721Wrapper,token_ERC721_extensions,token_ERC1155,utils]
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      
      - name: Check Docker Compose
        run: docker compose --version
      
      - name: Run Solo Tests
        run: npm run test:solo:gha:sharding --shard_id=${{matrix.sharding}}
