name: Thor compatibility tests

on:
  push:
    branches: [ thor-compatibility ]
  pull_request:
    branches: [ thor-compatibility ]

jobs:
  test-solo:
    name: Test Solo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      
      - name: Check Docker Compose
        run: docker compose --version
      
      - name: Run Solo Tests
        run: npm run test:solo:gha
        
  test-galactica:
    name: Test Galactica
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
        
      - name: Run Galactica Tests
        env:
          GALACTICA_DEVNET_MNEMONIC: ${{ secrets.GALACTICA_DEVNET_MNEMONIC }}
        run: npm run test:galactica:testnet
