name: Thor compatibility tests for galactica

on:
  workflow_dispatch:

jobs:
  test-galactica-devnet:
    name: Test Galactica Devnet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
        
      - name: Run Galactica Tests
        env:
          GALACTICA_DEVNET_MNEMONIC: ${{ secrets.GALACTICA_DEVNET_MNEMONIC }}
        run: npm run test:galactica:testnet
